export const zoneOptions = [
  { value: '', label: '請選擇' },
  { value: '第一種住宅區', label: '第一種住宅區' },
  { value: '第二種住宅區', label: '第二種住宅區' },
  { value: '第三種住宅區', label: '第三種住宅區' },
  { value: '第四種住宅區', label: '第四種住宅區' },
  { value: '第五種住宅區', label: '第五種住宅區' },
  { value: '第一種商業區', label: '第一種商業區' },
  { value: '第二種商業區', label: '第二種商業區' },
  { value: '第三種商業區', label: '第三種商業區' },
  { value: '第四種商業區', label: '第四種商業區' },
  { value: '第二種工業區', label: '第二種工業區' },
  { value: '第三種工業區', label: '第三種工業區' },
  { value: '行政區', label: '行政區' },
  { value: '文教區', label: '文教區' },
  { value: '倉庫區', label: '倉庫區' },
  { value: '風景區', label: '風景區' },
  { value: '農業區', label: '農業區' },
  { value: '保護區', label: '保護區' },
  { value: '行水區', label: '行水區' },
  { value: '保存區', label: '保存區' },
  { value: '特定專用區', label: '特定專用區' },
];

export const usageOptions = [
  { value: '', label: '請選擇' },
  { value: '公設', label: '公設' },
  { value: '公寓-5樓含以下無電梯', label: '公寓-5樓含以下無電梯' },
  { value: '透天厝', label: '透天厝' },
  { value: '店面-店舖', label: '店面-店舖' },
  { value: '辦公商業大樓', label: '辦公商業大樓' },
  { value: '住宅大樓-11層含以上有電梯', label: '住宅大樓-11層含以上有電梯' },
  { value: '華廈-10層含以下有電梯', label: '華廈-10層含以下有電梯' },
  { value: '套房', label: '套房' },
  { value: '農舍', label: '農舍' },
  { value: '增建-持分後坪數打對折', label: '增建-持分後坪數打對折' },
];
